name: Deploy - UI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Set env
        run: |
          echo "NEXT_PUBLIC_API_URL=https://newsletter-api.webdevcody.com" >> $GITHUB_ENV

      - name: Deploy ui
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          yarn workspaces @wdc-newsletter/ui build
          aws s3 cp ./ui/out s3://newsletter.webdevcody.com/ --recursive
