name: Deploy - API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Set env
        run: |
          echo "REGION=us-east-1" >> $GITHUB_ENV
          echo "HOST_NAME=https://newsletter.webdevcody.com" >> $GITHUB_ENV
          echo "DYNAMO_ENDPOINT=dynamodb.us-east-1.amazonaws.com" >> $GITHUB_ENV
          echo "SES_ENDPOINT=email.us-east-1.amazonaws.com" >> $GITHUB_ENV
          echo "TABLE_NAME=webdevcody_newsletter" >> $GITHUB_ENV

      - name: Deploy api
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: yarn deploy:api
