name: E2E - Cypress

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Run tests
        run: docker exec shell sh -c "CYPRESS_BASE_URL=http://ui:3000 yarn workspace @wdc-newsletter/e2e cypress && exit $?"
