name: Scripts - Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Run tests
        run: docker exec -it shell sh -c "yarn workspace @wdc-newsletter/scripts test:integration && exit $?"
